SWE74 Course Form Bugs
SWE-4103-Group-3/Project pull request #80
Opened 2017-11-18 14:36 UTC by jacsmith21

## Fixes #74

### Changes Proposed in this Pull Request:
- Fixes backend logic for transferring seating templates
- Fixes frontend logic for the disappearing rows / cols
- Fixed jQuery error in course form by moving JavaScript to the bottom (this may be unnecessary now)

2017-11-18 14:37 UTC, jacsmith21 commented on src/main/java/com/unb/tracker/web/CourseController.java
> +            newSeat.setCourse(courseReceive);
This is the line that fixed the backend!

2017-11-18 14:38 UTC, jacsmith21 commented on src/main/resources/templates/courseFormView.twig
> +        <div id="course-form-rows" class="md-form">
This line & the line below it fixed the frontend bug!

2017-11-18 21:26 UTC, brandon1024 requested changes
Mack and I have noticed some issues on this branch compared to develop. He is getting a 404 (I think). When I try to create a course and use a grid from another course, the course doesn't get created and im just redirected back to the instructor dashboard.

Other than that, these changes look good to me.

2017-11-18 21:26 UTC, brandon1024 commented on src/main/resources/templates/course.twig
> +				$('#deleteButton').attr('disabled',!this.checked);
Theres some pretty crazy tabs going on here!

2017-11-19 03:28 UTC, MackenzieJones commented
When I use seat grid on the dashboard for the first time, it works. But anytime after that, it doesn't. Using seat grid in the editor works though. No idea why.

2017-11-19 15:22 UTC, jacsmith21 commented
Ok @brandon1024 , I fixed that issue that you and Mack noticed!

2017-11-19 17:01 UTC, MackenzieJones approved these changes
Tested, looks good

2017-11-20 12:40 UTC, brandon1024 commented
I will review this morning :)

2017-11-20 19:50 UTC, brandon1024 approved these changes
Looks good. Merging

2017-11-20 19:50 UTC, merged